/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controlador;
import modelo.Camarero;
import modelo.Cocinero;
import modelo.JefeDeCocina;
import modelo.NodoIng;
import modelo.NodoPed;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class Principal extends javax.swing.JFrame {

    controlador controlador = new controlador();
    File archivo;
    File archivoBebidas;
    File archivoPostres;
    private NodoIng ptrPlatos;
    private NodoPed ptrPedidos;
    private NodoPed ptrFacturas;
    public static String Pedido;
    public static String beb;
    public static String postre;

    public Principal() {
        initComponents();
        ptrPlatos = null;
        ptrPedidos = null;
        ptrFacturas = null;

    }

    public void getPtrPlatos(NodoIng ptr) {
        this.ptrPlatos = ptr;

    }
    

    public File getArchivoIngrediente() {

        return this.archivo;
    }

    public File getArchivoPostre() {

        return this.archivoPostres;
    }

    public File getArchivobebida() {
        return this.archivoBebidas;

    }

    public void guardarArchivo() {
        // Crear un nuevo escritor
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(archivo))) {
            // Hallamos el numero de filas
            int filas = listaIngredientes.getRowCount();

            // Tomamos el modelo
            DefaultTableModel model = (DefaultTableModel) listaIngredientes.getModel();

            for (int i = 0; i < filas; ++i) {
                Object ingrediente = model.getValueAt(i, 0);
                Object cantidad = model.getValueAt(i, 1);

                bw.write(ingrediente + "," + cantidad);
                bw.newLine();
            }
        } catch (IOException ex) {
            // TODO enviar mensaje al usuario.
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cocina = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pedidosTable = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        Add = new javax.swing.JFrame();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        spin = new javax.swing.JSpinner();
        txtMesa = new javax.swing.JTextField();
        txtMesero = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        lbltipo = new javax.swing.JLabel();
        lblcolumna = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Menu = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaPlatos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bebidasTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        postresTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        JefeDeCocina = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        IngresarIngrediente = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_ingrediente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cant_ing = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btnActualizarIng = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaIngredientes = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtnombrearchivo = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        fc = new javax.swing.JFileChooser();
        AgregarPlatos = new javax.swing.JFrame();
        jScrollPane6 = new javax.swing.JScrollPane();
        listaIngredientes2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtPlato = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtIng1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtIng2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtIng3 = new javax.swing.JTextField();
        txtIng4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtcant1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtcant2 = new javax.swing.JTextField();
        txtcant3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtcant4 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        Cocinar = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblpedido = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        Cocina.setMinimumSize(new java.awt.Dimension(516, 430));
        Cocina.setResizable(false);
        Cocina.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COCINA");
        Cocina.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 100, 24));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton4.setText("Actualizar");

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Jefe de cocina");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton13.setText("Cocinar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(20, 20, 20))
        );

        Cocina.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 67, -1, -1));

        pedidosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Mesero", "Mesa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pedidosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedidosTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pedidosTable);
        if (pedidosTable.getColumnModel().getColumnCount() > 0) {
            pedidosTable.getColumnModel().getColumn(0).setResizable(false);
            pedidosTable.getColumnModel().getColumn(1).setResizable(false);
            pedidosTable.getColumnModel().getColumn(2).setResizable(false);
            pedidosTable.getColumnModel().getColumn(3).setResizable(false);
        }

        Cocina.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 67, 275, 110));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondox.net_fondo-con-lineas-azules_1728x1080.jpg"))); // NOI18N
        jLabel28.setText("jLabel28");
        Cocina.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 520));

        Add.setMinimumSize(new java.awt.Dimension(354, 284));
        Add.setResizable(false);
        Add.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Agregar Pedido");
        Add.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Cantidad:");
        Add.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 107, -1, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Mesa:");
        Add.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 140, -1, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Mesero:");
        Add.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 171, -1, -1));
        Add.getContentPane().add(spin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 104, -1, -1));
        Add.getContentPane().add(txtMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 137, 41, -1));
        Add.getContentPane().add(txtMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 168, 41, -1));

        jButton21.setText("Agregar Pedido");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        Add.getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 103, -1, -1));

        lbltipo.setForeground(new java.awt.Color(255, 255, 255));
        lbltipo.setText("jLabel7");
        Add.getContentPane().add(lbltipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        lblcolumna.setForeground(new java.awt.Color(255, 255, 255));
        lblcolumna.setText("jLabel7");
        Add.getContentPane().add(lblcolumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f3df92c17f5c1cc3209e60bc3831f3df.jpg"))); // NOI18N
        jLabel31.setText("jLabel31");
        Add.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 450));

        Menu.setFocusCycleRoot(false);
        Menu.setMinimumSize(new java.awt.Dimension(590, 360));
        Menu.setResizable(false);
        Menu.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plato", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaPlatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPlatosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaPlatos);
        if (listaPlatos.getColumnModel().getColumnCount() > 0) {
            listaPlatos.getColumnModel().getColumn(0).setResizable(false);
            listaPlatos.getColumnModel().getColumn(1).setResizable(false);
        }

        Menu.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 78, 161, 107));

        jLabel6.setFont(new java.awt.Font("SWMono", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BIENVENIDO AL RESTAURANTE DE TUS PESADILLAS");
        Menu.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 19, -1, -1));

        bebidasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bebida", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bebidasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bebidasTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(bebidasTable);
        if (bebidasTable.getColumnModel().getColumnCount() > 0) {
            bebidasTable.getColumnModel().getColumn(0).setResizable(false);
            bebidasTable.getColumnModel().getColumn(1).setResizable(false);
        }

        Menu.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 78, 173, 107));

        postresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Postre", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        postresTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postresTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(postresTable);
        if (postresTable.getColumnModel().getColumnCount() > 0) {
            postresTable.getColumnModel().getColumn(0).setResizable(false);
            postresTable.getColumnModel().getColumn(1).setResizable(false);
        }

        Menu.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 78, 159, 107));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton12.setText("Salir");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton22.setText("Help me");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButton22)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Menu.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jButton18.setText("Actualizar Bebidas");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        Menu.getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 49, 173, -1));

        jButton19.setText("Ver Platos");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        Menu.getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 49, 161, -1));

        jButton20.setText("Actualizar Postres");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        Menu.getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 49, 159, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f3df92c17f5c1cc3209e60bc3831f3df.jpg"))); // NOI18N
        jLabel30.setText("jLabel30");
        Menu.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 420));

        JefeDeCocina.setMinimumSize(new java.awt.Dimension(400, 302));
        JefeDeCocina.setResizable(false);

        jLabel2.setFont(new java.awt.Font("SWMono", 0, 18)); // NOI18N
        jLabel2.setText("JEFE DE COCINA");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton7.setText("Agregar Plato");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Agregar Ingrediente");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JefeDeCocinaLayout = new javax.swing.GroupLayout(JefeDeCocina.getContentPane());
        JefeDeCocina.getContentPane().setLayout(JefeDeCocinaLayout);
        JefeDeCocinaLayout.setHorizontalGroup(
            JefeDeCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JefeDeCocinaLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(JefeDeCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        JefeDeCocinaLayout.setVerticalGroup(
            JefeDeCocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JefeDeCocinaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        IngresarIngrediente.setMinimumSize(new java.awt.Dimension(500, 500));
        IngresarIngrediente.setResizable(false);

        jLabel3.setFont(new java.awt.Font("SWMono", 0, 18)); // NOI18N
        jLabel3.setText("AGREGAR INGREDIENTE");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Agregue ingrediente");

        jLabel5.setText("Cantidad");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(txt_ingrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(txt_cant_ing))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cant_ing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton9.setText("Agregar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Salir");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        btnActualizarIng.setText("Guardar");
        btnActualizarIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarIngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizarIng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizarIng)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addGap(29, 29, 29))
        );

        listaIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingrediente", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(listaIngredientes);
        if (listaIngredientes.getColumnModel().getColumnCount() > 0) {
            listaIngredientes.getColumnModel().getColumn(0).setResizable(false);
            listaIngredientes.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("Archivo:");

        jButton14.setText("Abrir");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnombrearchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtnombrearchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout IngresarIngredienteLayout = new javax.swing.GroupLayout(IngresarIngrediente.getContentPane());
        IngresarIngrediente.getContentPane().setLayout(IngresarIngredienteLayout);
        IngresarIngredienteLayout.setHorizontalGroup(
            IngresarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresarIngredienteLayout.createSequentialGroup()
                .addGroup(IngresarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IngresarIngredienteLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(IngresarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, IngresarIngredienteLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(IngresarIngredienteLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel3)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        IngresarIngredienteLayout.setVerticalGroup(
            IngresarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresarIngredienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(IngresarIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        AgregarPlatos.setMinimumSize(new java.awt.Dimension(570, 535));
        AgregarPlatos.setResizable(false);
        AgregarPlatos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaIngredientes2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingrediente", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(listaIngredientes2);
        if (listaIngredientes2.getColumnModel().getColumnCount() > 0) {
            listaIngredientes2.getColumnModel().getColumn(0).setResizable(false);
            listaIngredientes2.getColumnModel().getColumn(1).setResizable(false);
        }

        AgregarPlatos.getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 229, 141));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ingredientes actuales:");
        AgregarPlatos.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("AGREGAR PLATO");
        AgregarPlatos.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton15.setText("Crear Plato");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Salir");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("Agregar Ingredientes");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jButton17)
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton16)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        AgregarPlatos.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 68, -1, -1));

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setText("Nombre Plato:");

        jLabel14.setText("Ingrediente 1:");

        jLabel15.setText("Ingrediente 2:");

        jLabel16.setText("Ingrediente 3:");

        txtIng2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIng2ActionPerformed(evt);
            }
        });

        jLabel17.setText("Ingrediente 4:");

        jLabel18.setText("Cantidad 1:");

        txtcant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcant1ActionPerformed(evt);
            }
        });

        jLabel19.setText("Cantidad 2:");

        txtcant2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcant2ActionPerformed(evt);
            }
        });

        jLabel20.setText("Cantidad 3:");

        jLabel21.setText("Cantidad 4:");

        jLabel22.setText("Precio:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIng4))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIng3))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIng2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIng1))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcant1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcant3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(txtcant2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcant4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtprecio)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIng1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(txtcant1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtIng2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtcant2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtIng3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcant3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtIng4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcant4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        AgregarPlatos.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 68, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue-hd-background-wallpaper-1735.jpg"))); // NOI18N
        jLabel32.setText("jLabel32");
        AgregarPlatos.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 610));

        Cocinar.setMinimumSize(new java.awt.Dimension(355, 243));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("COCINAR");

        jButton11.setText("Aceptar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton23.setText("Denegar");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cocinar:");

        lblpedido.setText("jLabel9");

        javax.swing.GroupLayout CocinarLayout = new javax.swing.GroupLayout(Cocinar.getContentPane());
        Cocinar.getContentPane().setLayout(CocinarLayout);
        CocinarLayout.setHorizontalGroup(
            CocinarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CocinarLayout.createSequentialGroup()
                .addGroup(CocinarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CocinarLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel7))
                    .addGroup(CocinarLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButton11)
                        .addGap(58, 58, 58)
                        .addComponent(jButton23))
                    .addGroup(CocinarLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lblpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        CocinarLayout.setVerticalGroup(
            CocinarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CocinarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(39, 39, 39)
                .addGroup(CocinarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblpedido))
                .addGap(43, 43, 43)
                .addGroup(CocinarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton23))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_hd_169_tablas_azules_madera.jpg"))); // NOI18N
        jLabel29.setText("jLabel29");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(511, 160));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setForeground(new java.awt.Color(102, 153, 255));
        jButton1.setText("Cocina");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 84, 132, -1));

        jButton2.setForeground(new java.awt.Color(102, 153, 255));
        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 84, 134, -1));

        jButton3.setForeground(new java.awt.Color(102, 153, 255));
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 84, 127, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("RESTAURANTE LA PROSPERIDAD");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blue-hd-background-wallpaper-1735.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cocina.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Menu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Cocina.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JefeDeCocina.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        IngresarIngrediente.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        IngresarIngrediente.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        AgregarPlatos.setVisible(true);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Menu.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        if (!txt_cant_ing.getText().equals("") && !txt_ingrediente.getText().equals("")) {

            try {
                //Obtengo modelo de la tabla

                DefaultTableModel model = (DefaultTableModel) listaIngredientes.getModel();

                //Obtengo datos de los TextBox
                String ingrediente = this.txt_ingrediente.getText();
                int cantidad = Integer.parseInt(txt_cant_ing.getText());

                //Agrego a la Tabla los datos obtenidos
                model.addRow(new Object[]{ingrediente, cantidad});

                //Vacío los TextBox
                txt_ingrediente.setText("");
                txt_cant_ing.setText("");

            } catch (Exception e) {

            }
        } else {

            JOptionPane.showMessageDialog(null, "Espacios vacios", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        //Buscar si hay algun pedido seleccionado
        int fila = pedidosTable.getRowCount();
        System.out.println(fila);


    }//GEN-LAST:event_jButton13ActionPerformed

    private void btnActualizarIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarIngActionPerformed
        guardarArchivo();
    }//GEN-LAST:event_btnActualizarIngActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

        // Agregar filtro a FileChooser
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos .txt", "txt", "texto");
        fc.setFileFilter(filter);

        // Mostrar el FileChooser
        int opcion = fc.showOpenDialog(this);

        // Si el usuario escogió abrir
        if (opcion == JFileChooser.APPROVE_OPTION) {
            // Asignar archivo y nombre.
            archivo = fc.getSelectedFile();
            txtnombrearchivo.setText(archivo.getAbsolutePath());

            // Tomar el modelo de la tabla
            DefaultTableModel model = (DefaultTableModel) listaIngredientes.getModel();

            try (Scanner lector = new Scanner(archivo)) {
                // Mientras el archivo tenga otra línea.
                while (lector.hasNextLine()) {
                    // Pedir la linea
                    String linea = lector.nextLine();

                    // Separar los datos
                    String[] datos = linea.split(",");

                    // Convertir los datos
                    String ingrediente = datos[0];
                    int cantidad = Integer.parseInt(datos[1]);

                    // Agregamos datos a la tabla
                    model.addRow(new Object[]{ingrediente, cantidad});

                }
            } catch (FileNotFoundException ex) {
                // TODO enviar mensaje al usuario
            } catch (NumberFormatException ex) {
                // TODO enviar mensaje al usuario
            } catch (Exception ex) {
                // TODO enviar mensaje al usuario
            }
        }

    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        // Agregar filtro a FileChooser
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos .txt", "txt", "texto");
        fc.setFileFilter(filter);

        // Mostrar el FileChooser
        int opcion = fc.showOpenDialog(this);

        // Si el usuario escogió abrir
        if (opcion == JFileChooser.APPROVE_OPTION) {
            // Asignar archivo y nombre.
            archivo = fc.getSelectedFile();

            // Tomar el modelo de la tabla
            DefaultTableModel model = (DefaultTableModel) listaIngredientes2.getModel();

            try (Scanner lector = new Scanner(archivo)) {
                // Mientras el archivo tenga otra línea.
                while (lector.hasNextLine()) {
                    // Pedir la linea
                    String linea = lector.nextLine();

                    // Separar los datos
                    String[] datos = linea.split(",");

                    // Convertir los datos
                    String ingrediente = datos[0];
                    int cantidad = Integer.parseInt(datos[1]);

                    // Agregamos datos a la tabla
                    model.addRow(new Object[]{ingrediente, cantidad});

                }
            } catch (FileNotFoundException ex) {
                // TODO enviar mensaje al usuario
            } catch (NumberFormatException ex) {
                // TODO enviar mensaje al usuario
            } catch (Exception ex) {
                // TODO enviar mensaje al usuario
            }
        }


    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        AgregarPlatos.setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

        //VERIFICO QUE NO HAYAN ESPACIOS VACIOS
        if (!txtPlato.getText().equals("") && !txtIng1.getText().equals("") && !txtIng2.getText().equals("") && !txtIng3.getText().equals("") && !txtIng4.getText().equals("") && !txtcant1.getText().equals("") && !txtcant2.getText().equals("") && !txtcant3.getText().equals("") && !txtcant4.getText().equals("") && !txtprecio.getText().equals("")) {

            try {

                //SOLO DEJA AGREGAR PLATOS SI LOS INGREDIENTE SON SUFICIENTES
                controlador.crearPlato(txtPlato.getText(), txtIng1.getText(), txtIng2.getText(), txtIng3.getText(), txtIng4.getText(), Integer.parseInt(txtcant1.getText()), Integer.parseInt(txtcant2.getText()), Integer.parseInt(txtcant3.getText()), Integer.parseInt(txtcant4.getText()), archivo, ptrPlatos, Integer.parseInt(txtprecio.getText()));
                txtPlato.setText("");
                txtIng1.setText("");
                txtIng2.setText("");
                txtIng3.setText("");
                txtIng4.setText("");
                txtcant1.setText("");
                txtcant2.setText("");
                txtcant3.setText("");
                txtcant4.setText("");
                this.txtprecio.setText("");
                JOptionPane.showMessageDialog(null, "Plato agregado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                ///MOSTRAR LISTA ENSEGUIDA EN MENU
                ptrPlatos = controlador.getPtr();
                mostrarLista(ptrPlatos);

                //SI LA MUESTRA
            } catch (Exception e) {

            }

        } else {

            JOptionPane.showMessageDialog(null, "Espacios vacios", "Error:", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButton15ActionPerformed

    private void txtIng2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIng2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIng2ActionPerformed

    private void txtcant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcant1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcant1ActionPerformed

    private void txtcant2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcant2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcant2ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

        DefaultTableModel model = (DefaultTableModel) bebidasTable.getModel();
        limpiarTabla(bebidasTable);
        // Agregar filtro a FileChooser
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos .txt", "txt", "texto");
        fc.setFileFilter(filter);

        // Mostrar el FileChooser
        int opcion = fc.showOpenDialog(this);

        // Si el usuario escogió abrir
        if (opcion == JFileChooser.APPROVE_OPTION) {
            // Asignar archivo y nombre.
            archivoBebidas = fc.getSelectedFile();

            // Tomar el modelo de la tabla
            model = (DefaultTableModel) bebidasTable.getModel();

            try (Scanner lector = new Scanner(archivoBebidas)) {
                // Mientras el archivo tenga otra línea.
                while (lector.hasNextLine()) {
                    // Pedir la linea
                    String linea = lector.nextLine();

                    // Separar los datos
                    String[] datos = linea.split(",");

                    // Convertir los datos
                    String bebida = datos[0];
                    int precio = Integer.parseInt(datos[1]);

                    // Agregamos datos a la tabla
                    model.addRow(new Object[]{bebida, precio});

                }
            } catch (FileNotFoundException ex) {
                // TODO enviar mensaje al usuario
            } catch (NumberFormatException ex) {
                // TODO enviar mensaje al usuario
            } catch (Exception ex) {
                // TODO enviar mensaje al usuario
            }
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed

        DefaultTableModel model = (DefaultTableModel) postresTable.getModel();
        this.limpiarTabla(postresTable);
        // Agregar filtro a FileChooser
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos .txt", "txt", "texto");
        fc.setFileFilter(filter);

        // Mostrar el FileChooser
        int opcion = fc.showOpenDialog(this);

        // Si el usuario escogió abrir
        if (opcion == JFileChooser.APPROVE_OPTION) {
            // Asignar archivo y nombre.
            archivoPostres = fc.getSelectedFile();

            // Tomar el modelo de la tabla
            model = (DefaultTableModel) postresTable.getModel();

            try (Scanner lector = new Scanner(archivoPostres)) {
                // Mientras el archivo tenga otra línea.
                while (lector.hasNextLine()) {
                    // Pedir la linea
                    String linea = lector.nextLine();

                    // Separar los datos
                    String[] datos = linea.split(",");

                    // Convertir los datos
                    String bebida = datos[0];
                    int precio = Integer.parseInt(datos[1]);

                    // Agregamos datos a la tabla
                    model.addRow(new Object[]{bebida, precio});

                }
            } catch (FileNotFoundException ex) {
                // TODO enviar mensaje al usuario
            } catch (NumberFormatException ex) {
                // TODO enviar mensaje al usuario
            } catch (Exception ex) {
                // TODO enviar mensaje al usuario
            }
        }

    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed

        if (ptrPlatos == null) {

            JOptionPane.showMessageDialog(null, "No hay platos creados", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            mostrarLista(ptrPlatos);

        }


    }//GEN-LAST:event_jButton19ActionPerformed

    public static String getBeb() {
        return beb;
    }

    public static String getPostre() {
        return postre;
    }

    private void bebidasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bebidasTableMouseClicked
        if (evt.getClickCount() == 2) {
            lbltipo.setText("Bebidas");
            String columna = String.valueOf(bebidasTable.getSelectedRow());
            lblcolumna.setText(columna);
            Add.setVisible(true);

        }
    }//GEN-LAST:event_bebidasTableMouseClicked

    private void listaPlatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPlatosMouseClicked
        if (evt.getClickCount() == 2) {
            lbltipo.setText("Platos");
            String columna = String.valueOf(listaPlatos.getSelectedRow());
            lblcolumna.setText(columna);
            Add.setVisible(true);
        }

    }//GEN-LAST:event_listaPlatosMouseClicked

    private void postresTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postresTableMouseClicked
        if (evt.getClickCount() == 2) {
            lbltipo.setText("Postres");
            String columna = String.valueOf(postresTable.getSelectedRow());
            lblcolumna.setText(columna);
            Add.setVisible(true);
        }
    }//GEN-LAST:event_postresTableMouseClicked

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed

        if (!txtMesa.getText().equals("") && !txtMesero.getText().equals("") && Integer.parseInt(spin.getValue().toString()) > 0) {
            try {

                //ME AYUDO DE LOS LABELS QUE PUSE
                int cant = Integer.parseInt(spin.getValue().toString());
                int row = Integer.parseInt(lblcolumna.getText());
                String tipo = lbltipo.getText();
                if (tipo.equals("Bebidas")) {
                    //Obtengo valores de la lista

                    String tipoPedido = "Bebida";
                    String bebida = bebidasTable.getValueAt(row, 0).toString();
                    int precio = Integer.parseInt(bebidasTable.getValueAt(row, 1).toString());
                    controlador.tomarPedido(tipoPedido, bebida, precio, cant, txtMesa.getText(), txtMesero.getText(), ptrPedidos);
                    ptrPedidos = controlador.getPtrPedido();
                    System.out.println("Esta funcionando");
                    mostrarLista(ptrPedidos, pedidosTable);
                    //Llamo la funcion agregar pedido
                } else if (tipo.equals("Postres")) {

                    String tipoPedido = "Postre";
                    String postre = postresTable.getValueAt(row, 0).toString();
                    int precio = Integer.parseInt(postresTable.getValueAt(row, 1).toString());
                    controlador.tomarPedido(tipoPedido, postre, precio, cant, txtMesa.getText(), txtMesero.getText(), ptrPedidos);
                    ptrPedidos = controlador.getPtrPedido();
                    mostrarLista(ptrPedidos, pedidosTable);

                } else if (tipo.equals("Platos")) {
                    String tipoPedido = "Plato";
                    String plato = listaPlatos.getValueAt(row, 0).toString();
                    int precio = Integer.parseInt(listaPlatos.getValueAt(row, 1).toString());
                    controlador.tomarPedido(tipoPedido, plato, precio, cant, txtMesa.getText(), txtMesero.getText(), ptrPedidos);
                    ptrPedidos = controlador.getPtrPedido();
                    mostrarLista(ptrPedidos, pedidosTable);
                } else {
                    JOptionPane.showMessageDialog(null, "Debe seleccionar algo de las listas de arriba", "Error:", JOptionPane.ERROR_MESSAGE);
                }

                txtMesa.setText("");
                txtMesero.setText("");
                spin.setValue(0);
                Add.setVisible(false);

            } catch (Exception e) {

            }
        } else {

            JOptionPane.showMessageDialog(null, "Hay espacios vacio, debe completarlos todos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void pedidosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedidosTableMouseClicked

        if (evt.getClickCount() == 2) {

            //Pedido = pedidosTable.getValueAt(fila, 0).toString();
            int v = pedidosTable.getSelectedRow();
            lblpedido.setText(pedidosTable.getValueAt(v, 0).toString());
            Cocinar.setVisible(true);

        }


    }//GEN-LAST:event_pedidosTableMouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        //OBTENGO LA FILA SELECCIONADA  
        int v = pedidosTable.getSelectedRow();

        //OBTENGO LOS DATOS PARA PASAR A COCINAR
        String pedido = pedidosTable.getValueAt(v, 0).toString();
        int cant = Integer.parseInt(pedidosTable.getValueAt(v, 1).toString());
        String mesero = pedidosTable.getValueAt(v, 2).toString();
        String mesa = pedidosTable.getValueAt(v, 3).toString();

        //PASO A LAS FUNCIONES DEL CONTROLADOR PARA AGREGAR A LA LISTA DE FACTURAS
        controlador.cocinar(pedido, cant, mesero, mesa, ptrFacturas, ptrPedidos);
        ptrPedidos = controlador.getPtrPedido();
        this.ptrFacturas = controlador.getPtrFacturas();
        mostrarLista(ptrPedidos, pedidosTable);

        Cocinar.setVisible(false);


    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        lblpedido.setText("");
        Cocinar.setVisible(false);
    }//GEN-LAST:event_jButton23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Add;
    private javax.swing.JFrame AgregarPlatos;
    private javax.swing.JFrame Cocina;
    private javax.swing.JFrame Cocinar;
    private javax.swing.JFrame IngresarIngrediente;
    private javax.swing.JFrame JefeDeCocina;
    private javax.swing.JFrame Menu;
    public javax.swing.JTable bebidasTable;
    private javax.swing.JButton btnActualizarIng;
    private javax.swing.JFileChooser fc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblcolumna;
    private javax.swing.JLabel lblpedido;
    private javax.swing.JLabel lbltipo;
    private javax.swing.JTable listaIngredientes;
    private javax.swing.JTable listaIngredientes2;
    private javax.swing.JTable listaPlatos;
    private javax.swing.JTable pedidosTable;
    private javax.swing.JTable postresTable;
    private javax.swing.JSpinner spin;
    private javax.swing.JTextField txtIng1;
    private javax.swing.JTextField txtIng2;
    private javax.swing.JTextField txtIng3;
    private javax.swing.JTextField txtIng4;
    private javax.swing.JTextField txtMesa;
    private javax.swing.JTextField txtMesero;
    private javax.swing.JTextField txtPlato;
    private javax.swing.JTextField txt_cant_ing;
    private javax.swing.JTextField txt_ingrediente;
    private javax.swing.JTextField txtcant1;
    private javax.swing.JTextField txtcant2;
    private javax.swing.JTextField txtcant3;
    private javax.swing.JTextField txtcant4;
    private javax.swing.JTextField txtnombrearchivo;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables

    private void limpiarTabla(JTable listaIngredientes) {

        DefaultTableModel model = (DefaultTableModel) listaIngredientes.getModel();
        model.setRowCount(0);
    }

    public void mostrarLista(NodoIng ptr) {

        DefaultTableModel model = (DefaultTableModel) listaPlatos.getModel();
        limpiarTabla(listaPlatos);
        NodoIng p = ptr;
        while (p != null) {
            model.addRow(new Object[]{p.Plato, p.precio});
            p = p.link;
        }

    }

    public void mostrarLista(NodoPed ptr, JTable lista) {
        DefaultTableModel model = (DefaultTableModel) lista.getModel();
        limpiarTabla(lista);
        NodoPed p = ptr;
        while (p != null) {
            model.addRow(new Object[]{p.Pedido, p.cantidad, p.mesero, p.mesa});
            p = p.link;
        }

    }

}
